### PR TITLE
Enable option to use custom mjml parser instead of default one

### PR DESCRIPTION
**Pull request by pavelstencl**
Hi @artf ,

Thank you for your repository. It's fantastic! We've implemented our custom MJML-browser parser with additional components, but we're encountering issues using it in GrapesJS/mjml. 

So I've included an option in the GrapesJS/mjml plugin config to override the default MJML parser. Would it be feasible to incorporate this feature into your package?

Thanks and cheers!

### CODE REVIEW

**Comment by pavelstencl** [comment]
@artf Hi what do you think. Would be possible to add this feature to a master? Thanks, Pavel

**Comment by RakulAgn** [comment]
@artf This is a good option to use. Why can't you merge and approve this? I am also looking forward to using custom MJML components."

**Comment by RakulAgn** [comment]
@pavelstencl Having Complete Demo is Great

**Review by artf — APPROVED** [review]
Thanks @pavelstencl this is an awesome addition.
Sorry if it took some much time to finally merge it 😓

**Pull request merged**
